### ISSUE TITLE
doesn't support japanese `{}` and `()`

### ISSUE THREAD

**Issue by Maxhodges** [joeellis/showdown-kanji#1]
When typing Japanese in markdown, I need to constantly switch between English and Japanese using the IME because the markdown depends on English `()` and `{}` characters, but doesn't support Japanese versions of these characters.

so this works:
`{私}(わたし)はジョーと{申}(もう)します`

 but this doesn't work properly
`｛ 寿司｝（すし）｛私｝（わたし）`

have you considered adding support for Japanese curly brackets and parentheses? or did you have a specific reason for not including them?

Cheers!

**Comment by joeellis** [comment]
@Maxhodges Actually I have the exact same issue, and built in support for Japanese parens specifically so I didn't have to keep switching (test here: https://github.com/joeellis/showdown-kanji/blob/master/test/test-kanji-extension.js#L14).  But I wonder if maybe the brackets are the problem - I don't see anything in the regex that would account for multi-byte brackets

I'll look into it this week if I can.  In the meantime, if you want to try and make a small modification to the regex to see if you can get it to work, I'd happily accept any PR for it that comes with a test proving it works

**Comment by Maxhodges** [comment]
seems your test was using western-style squiggly wings "{}"
I updated the test to use japanese style "｛｝"
will see if I can figure out the regex

**Comment by joeellis** [comment]
Closing this as this was fixed in https://github.com/joeellis/showdown-kanji/pull/3
